<?php

class ProcessImageMinimize extends WireData implements Module, ConfigurableModule {

    const statusInit = 0;
    const statusPushed = 1;
    const statusProcessedSuccess = 2;
    const statusProcessedError = 3;
    const statusDone = 4;

    public static function getModuleInfo() {
        return array(
            'title' => 'minimize.pw',
            'author' => 'Conclurer GbR',
            'version' => 150
        );
    }

    /**
     * Return an InputfieldsWrapper of Inputfields used to configure the class
     *
     * @param array $data Array of config values indexed by field name
     * @return InputfieldsWrapper
     *
     */
    public static function getModuleConfigInputfields(array $data)
    {
        // TODO: Implement getModuleConfigInputfields() method.
    }


    public function pushToLocalQueue ($imgPath) {
        // Check if image is already in queue
        $object = MinimizeQueueObject::getByPath($imgPath);
        if ($object->exists()) return false;

        $pushObject = new MinimizeQueueObject();
        $pushObject->status = ProcessImageMinimize::statusInit;
        $pushObject->path = $imgPath;
        $pushObject->save();

        return true;
    }


}